//! Localization: translated UI strings with per-string translator context.
//!
//! `strings.json` in the repository root is the source of truth. It holds, per
//! string, the stable key, the English text, the German text and the *context*
//! — where the string appears and what it means. `build.rs` generates the
//! modules included below, so the context cannot drift away from the text.
//!
//! Adding a language means adding its text to `strings.json` and extending the
//! two matches in this file. `build.rs` fails the build if a string has no
//! usable context, because a translator works from the JSON file alone.
//!
//! Adding a *new string* means adding it to `strings.json` and a variant to
//! [`Msg`]; the compiler then points at every place that needs updating.

use std::fmt;

/// Everything generated by `build.rs` from `strings.json`, in one module so
/// the generated `match` arms can refer to each other with short paths.
mod gen {
    /// English, the source language and the fallback.
    pub mod en {
        include!(concat!(env!("OUT_DIR"), "/en.rs"));
    }

    /// German.
    pub mod de {
        include!(concat!(env!("OUT_DIR"), "/de.rs"));
    }

    include!(concat!(env!("OUT_DIR"), "/enum.rs"));
    include!(concat!(env!("OUT_DIR"), "/text.rs"));
    include!(concat!(env!("OUT_DIR"), "/lookup.rs"));
    include!(concat!(env!("OUT_DIR"), "/notes.rs"));
}

pub use gen::Msg;

impl Msg {
    /// English text, also the fallback for languages that lack this key.
    pub fn text(self) -> &'static str {
        gen::text(self)
    }

    /// Context for translators, generated from the same JSON file as the text.
    ///
    /// Not read at runtime: this exists so a string cannot lose its context
    /// while the translation sheet is generated from the same source.
    #[cfg_attr(not(test), allow(dead_code))]
    pub fn note(self) -> &'static str {
        gen::note(self)
    }
}

/// The language the UI is currently rendered in.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Language {
    #[default]
    English,
    German,
}

impl Language {
    /// The text in this language, falling back to English for missing keys.
    pub fn text(self, msg: Msg) -> &'static str {
        match self {
            Language::English => msg.text(),
            Language::German => gen::de_text(msg),
        }
    }

    /// Switches to the next language, for the temporary key binding.
    pub fn other(self) -> Self {
        match self {
            Language::English => Language::German,
            Language::German => Language::English,
        }
    }
}

impl fmt::Display for Language {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Language::English => "en",
            Language::German => "de",
        })
    }
}

#[cfg(test)]
mod tests {
    use super::gen::ALL;
    use super::*;

    /// A string without usable context is the failure mode that makes
    /// translation guesswork, so the file must never contain one.
    #[test]
    fn every_message_has_context_for_translators() {
        for msg in ALL {
            assert!(
                msg.note().len() > 20,
                "{msg:?} has no usable translation context"
            );
        }
    }

    /// Catches a language file that was copied but never filled in. Runs over
    /// every string automatically, so adding a key to `strings.json` is enough —
    /// a new string that was never translated fails here.
    ///
    /// Excluded are the keys where the words genuinely coincide (`<DIR>`,
    /// `<UP>`, "Name") and the internal error, whose German wording is free to
    /// change. `build.rs` emits `IDENTICAL` for the excluded set so this list
    /// cannot drift.
    #[test]
    fn every_string_is_actually_translated() {
        for msg in ALL {
            if is_allowed_identical(*msg) {
                continue;
            }
            assert_ne!(
                Language::English.text(*msg),
                Language::German.text(*msg),
                "{msg:?} is identical in both languages — never translated?"
            );
        }
    }

    /// Keys whose English and German are legitimately the same.
    ///
    /// `ColumnName` and `DialogMkdirLabel` are both "Name": the word is the same
    /// in both languages. `MarkerDir`/`MarkerUp` are a Norton Commander
    /// convention and are never translated at all.
    fn is_allowed_identical(msg: Msg) -> bool {
        matches!(
            msg,
            Msg::ColumnName | Msg::MarkerDir | Msg::MarkerUp | Msg::DialogMkdirLabel
        )
    }

    /// The marker convention is deliberately not translated.
    #[test]
    fn markers_stay_identical_across_languages() {
        for lang in [Language::English, Language::German] {
            assert_eq!(lang.text(Msg::MarkerDir), "<DIR>");
            assert_eq!(lang.text(Msg::MarkerUp), "<UP>");
        }
    }

    /// Templates that interpolate values must use the same placeholder names in
    /// every language, otherwise one language shows `{reason}` to the user.
    #[test]
    fn placeholders_match_across_languages() {
        for msg in ALL {
            let en = Language::English.text(*msg);
            let de = Language::German.text(*msg);
            for placeholder in ["{path}", "{reason}"] {
                assert_eq!(
                    en.contains(placeholder),
                    de.contains(placeholder),
                    "{msg:?} uses {placeholder} in one language but not the other"
                );
            }
        }
    }
}

#[cfg(test)]
mod dump {
    use super::gen::ALL;
    use super::Language;

    /// Not a test: prints every string with its context and all translations,
    /// so a translator can work from this output alone.
    /// Run with `cargo test dump -- --nocapture`.
    #[test]
    fn print_translation_sheet() {
        for msg in ALL {
            println!("\n## {msg:?}");
            println!("EN    {}", Language::English.text(*msg));
            println!("DE    {}", Language::German.text(*msg));
            println!("NOTE  {}", msg.note());
        }
        println!("\n( {} strings )", ALL.len());
    }
}
